add_newline = false

format = """
$status \
$username\
$hostname\
$ruby\
$python\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character"""

[character]
success_symbol = "[\\$](#33cccc)"
error_symbol = "[\\$](#33cccc)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "⋌ "

[ruby]
format = "[$symbol($version )]($style)"
symbol = "[✦ ](red)"

[python]
format = '[$symbol($version)\(($virtualenv)\)]($style) '
symbol = "§ "

[git_status]
style = "bold purple"
deleted = "-"

[git_state]
style = "red"
